[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.5",
    "telethon>=1.41.2",
    "tgcrypto>=1.2.5",
    "youtube-dl>=2021.12.17",
    "yt-dlp>=2025.9.5",
]
